### ISSUE TITLE
Add pull request template

### ISSUE THREAD

**Issue by sohan2410** [sohan2410/crypto-transactions#3]
- You can refer the  docs from [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)
- Please add best practice PR template

**Comment by dasShounak** [comment]
I can help

**Comment by codesmith25103** [comment]
@sohan2410 sir, I am facing problem to set up this project locally. Can you guide me through the process so I could contribute in it?

**Comment by sohan2410** [comment]
> @sohan2410 sir, I am facing problem to set up this project locally. Can you guide me through the process so I could contribute in it?

Can you please specify where you are getting problem

**Comment by codesmith25103** [comment]
<img width="706" alt="image" src="https://user-images.githubusercontent.com/102778847/194726943-b2b99be6-dae7-40df-b2db-eca41da424a1.png">
sir i am getting this error while trying to run  server

**Comment by sohan2410** [comment]
Did you create . env file and write valid mongo uri?

**Comment by codesmith25103** [comment]
Sir. I have created .env file, but was not able to find mongo url.

**Comment by sohan2410** [comment]
you can use local MongoDB URL like : `mongodb://localhost:27017/crypto-transactions`

**Comment by Aaroh1** [comment]
Hey @sohan2410 ! Can i work on this issue?

**Comment by sohan2410** [comment]
sure @Aaroh1, you can go ahead
